name: i_wish
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_container: ^1.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # - assets/icons/
    - assets/images/
    # - assets/photos/
fonts:
    - family: CoFoSans
      fonts:
        - asset: fonts/CoFoSans-Regular.ttf
      

    - family: AbhayaLibre
      fonts:
        # - asset: fonts/AbhayaLibre-Regular.ttf
        # # - asset: fonts/AbhayaLibre-Bold.ttf
        # # - asset: fonts/AbhayaLibre-ExtraBold.ttf
        # # - asset: fonts/AbhayaLibre-Medium.ttf
        # # # - asset: fonts/AbhayaLibre-SemiBold.ttf
        - asset: fonts/AbhayaLibre_medium.ttf
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700